// set the html UI values to the config values
window.onload = function() {
  console.log(a);
  console.log(projekte);
  console.log(schueler);
  // a is an array generated by php code and has the following structure
  // var a = ["schuelerAnzahl", "checkedMonday", ..., "checkedFriday", "firstDay"]
  var stages = [
    '<option value="0">#1 Nicht veröffentlicht</option>',
    '<option value="1">#2 Projekte können eingereicht werden</option>',
    '<option value="2">#3 Projekt-Einreichung geschlossen</option>',
    '<option value="3">#4 Wahl-Interface geöffnet</option>',
    '<option value="4">#5 Wahlen abgeschlossen</option>'
  ];
  $("#stageSelect").append($(stages[a["Stage"]]));
  for(var i = 0; i < 5; i++){
    if(i == a["Stage"]) {
      continue;
    }
    $("#stageSelect").append($(stages[i]));
  }

  $("#inputSchuelerAnzahl").val(parseInt(a['Schüleranzahl']));

  // Wochentage:
  // convert the string into a bool
  a["Montag"] = (a["Montag"] == 'true');
  $("#montag").prop("checked", a["Montag"]);
  //disable projekt-settings, when inital phase is over
  if(a['Stage'] != 0){
    $("#montag").prop("disabled", true);
    $("#montag").addClass("disabled");
  }
  a["Dienstag"] = (a["Dienstag"] == 'true');
  $("#dienstag").prop("checked", a["Dienstag"]);
  //disable projekt-settings, when inital phase is over
  if(a['Stage'] != 0){
    $("#dienstag").prop("disabled", true);
    $("#dienstag").addClass("disabled");
  }
  a["Mittwoch"] = (a["Mittwoch"] == 'true');
  $("#Mittwoch").prop("checked", a["Mittwoch"]);
  //disable projekt-settings, when inital phase is over
  if(a['Stage'] != 0){
    $("#mittwoch").prop("disabled", true);
    $("#mittwoch").addClass("disabled");
  }
  a["Donnerstag"] = (a["Donnerstag"] == 'true');
  $("#donnerstag").prop("checked", a["Donnerstag"]);
  //disable projekt-settings, when inital phase is over
  if(a['Stage'] != 0){
    $("#donnerstag").prop("disabled", true);
    $("#donnerstag").addClass("disabled");
  }
  a["Freitag"] = (a["Freitag"] == 'true');
  $("#freitag").prop("checked", a["Freitag"]);
  //disable projekt-settings, when inital phase is over
  if(a['Stage'] != 0){
    $("#freitag").prop("disabled", true);
    $("#freitag").addClass("disabled");
  }

  // convert the string into a bool
  a["SchuleAmErstenVormittag"] = (a["SchuleAmErstenVormittag"] == 'true');
  $("#firstDaytrue").prop("checked", a["SchuleAmErstenVormittag"]);
  //disable projekt-settings, when inital phase is over
  if(a["Stage"] != 0){
    $("#firstDaytrue").prop("disabled", true);
    $("#firstDaytrue").addClass("disabled");
    $("#firstDayfalse").prop("disabled", true);
    $("#firstDayfalse").addClass("disabled");
  }


  //erstellen der projekte- und schüler-tabellen
  console.log("Creating: projekteTable");
  $.each(projekte[0], function(index, value){
    $("#projekteTable>thead>tr").append($("<th>" + index  + "</th>"));
  });
  $.each(projekte, function(index, value){
    $("#projekteTable>tbody").append($("<tr></tr>"));
    $.each(projekte[index], function(index, value){
      $("#projekteTable>tbody:last-child").append($("<td>" + value + "</td>"));
    });
  });

  console.log("Creating: schuelerTable");
  $.each(schueler[0], function(index, value){
    $("#schuelerTable>thead>tr").append($("<th>" + index  + "</th>"));
  });
  $.each(schueler, function(index, value){
    $("#schuelerTable>tbody").append($("<tr></tr>"));
    $.each(schueler[index], function(index, value){
      $("#schuelerTable>tbody:last-child").append($("<td>" + value + "</td>"));
    });
  });
}

//We don't know why we need it, but now it works!!! Don't delete it !!!!!!!
$('input:checkbox').on('click', function(e) {
    e.stopImmediatePropagation();
    var checked = (e.currentTarget.checked) ? false : true;
    e.currentTarget.checked = (checked) ? false : checked.toString();
});

$('input:radio').on('click', function(e) {
    e.stopImmediatePropagation();
    var checked = (e.currentTarget.checked) ? false : true;
    e.currentTarget.checked = (checked) ? false : checked.toString();
});
