USE projektwahl;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";
CREATE TABLE `PROJEKTE` (
  `ID` int(11) NOT NULL,
  `Name` text NOT NULL,
  `Beschreibung` longtext NOT NULL,
  `Min_Klasse` int(11) UNSIGNED NOT NULL DEFAULT '5',
  `Max_Klasse` int(11) UNSIGNED NOT NULL DEFAULT '12',
  `Min_Plaetze` int(11) UNSIGNED NOT NULL DEFAULT '10',
  `Max_Plaetze` int(11) UNSIGNED NOT NULL DEFAULT '30',
  `Betreuer` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `SCHUELERWAHL` (
  `ID` int(11) NOT NULL,
  `Vorname` text NOT NULL,
  `Nachname` text NOT NULL,
  `Klassenstufe` int(11) NOT NULL,
  `WahlID` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `WAHL` (
  `WahlID` int(11) NOT NULL,
  `Wahl1` int(11) NOT NULL,
  `Wahl2` int(11) NOT NULL,
  `Wahl3` int(11) NOT NULL,
  `Wahl4` int(11) NOT NULL,
  `Wahl5` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE `PROJEKTE`
  ADD PRIMARY KEY (`ID`);
ALTER TABLE `SCHUELERWAHL`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `Projektwahl` (`WahlID`);
ALTER TABLE `WAHL`
  ADD PRIMARY KEY (`WahlID`),
  ADD KEY `Wahl1` (`Wahl1`),
  ADD KEY `Wahl2` (`Wahl2`),
  ADD KEY `Wahl3` (`Wahl3`),
  ADD KEY `Wahl4` (`Wahl4`),
  ADD KEY `Wahl5` (`Wahl5`);
ALTER TABLE `PROJEKTE`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `SCHUELERWAHL`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `WAHL`
  MODIFY `WahlID` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `SCHUELERWAHL`
  ADD CONSTRAINT `Projektwahl` FOREIGN KEY (`WahlID`) REFERENCES `WAHL` (`wahlid`);
ALTER TABLE `WAHL`
  ADD CONSTRAINT `Wahl1` FOREIGN KEY (`Wahl1`) REFERENCES `PROJEKTE` (`id`),
  ADD CONSTRAINT `Wahl2` FOREIGN KEY (`Wahl2`) REFERENCES `PROJEKTE` (`id`),
  ADD CONSTRAINT `Wahl3` FOREIGN KEY (`Wahl3`) REFERENCES `PROJEKTE` (`id`),
  ADD CONSTRAINT `Wahl4` FOREIGN KEY (`Wahl4`) REFERENCES `PROJEKTE` (`id`),
  ADD CONSTRAINT `Wahl5` FOREIGN KEY (`Wahl5`) REFERENCES `PROJEKTE` (`id`);
COMMIT;
